# Generated by Django 3.2 on 2022-11-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20210615_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=10, null=True),
        ),
    ]
